### ISSUE TITLE
Massive collision box in Avery's Office

### ISSUE THREAD

**Issue by TheLazyHatGuy** [DucksWorth-Studios/ProjectGoose#244]
![image](https://user-images.githubusercontent.com/1010359/114428918-b18a9500-9bb4-11eb-95f7-f4780f447638.png)

This box is attached to duckswoth_Photo which is a Missing Prefab

**Comment by TheLazyHatGuy** [comment]
Fixed in #248

**Comment by AndyCarolan9** [comment]
the obj file was missing from the project files in git. This broke the prefab and reset the collision box it had. The files were reimported and the prefab was remade to fix
