### ISSUE TITLE
Massive memory leak

### ISSUE THREAD

**Issue by TheLazyHatGuy** [DucksWorth-Studios/ProjectGoose#249]
![image](https://user-images.githubusercontent.com/1010359/114471432-8a4dbb00-9be8-11eb-8dc2-5a27d90b6238.png)

At random points when playing any scene in the Unity Editor (and in built versions of the game) the engine will consume all remaining system RAM and crash

**Comment by TheLazyHatGuy** [comment]
Okay some updates on my research into the memory leak issue
1. It is random
2. Updating to Unity 2020.3.3f1 does not fix it
3. Profiler crashes so we can't find a source of the leak
4. This is a known bug with some projects since 2017
5. It may be a problem with AMD CPUs

**Comment by TheLazyHatGuy** [comment]
I have submitted the bug to Unity (Case number: 1328723). 
Awaiting feedback

**Comment by TheLazyHatGuy** [comment]
Aaron has discovered that the memory leak is possibly due to the fixes implemented to the Outline script.

The next cause of action is to find out if there is a way to keep the fixes to the Outline script but avoid the memory leak bug.

**Comment by TheLazyHatGuy** [comment]
This turned out to be a series of bugs with the outline script and its execution order. 

The fix that allowed the outline script to take reference of all mesh renderers for an was also causing a memory leak when executed on many objects when loading the lab scene.

The resolution to this was to ensure that the outline is completely disabled on load and only enabled were needed, as well as delaying taking in reference to all mesh renderers.

**Comment by TheLazyHatGuy** [comment]
Bug confirmed resolved by Andrew and myself. 

Awaiting additional confirmation from Tomas.

**Comment by TheReverseBrother** [comment]
Tested the loading 5 times like the original tests issue seems resolved
