### ISSUE TITLE
Hand Still Colliding with watch

### ISSUE THREAD

**Issue by TheReverseBrother** [DucksWorth-Studios/ProjectGoose#262]
Hand is still colliding with watch when walking backwards

**Comment by TheLazyHatGuy** [comment]
In my testing, the only collision the watch has is to disable the menu. More info required

**Comment by TheLazyHatGuy** [comment]
According to Aaron's video, the hands appear to rotate when walking backwards. Further testing required.

**Comment by TheLazyHatGuy** [comment]
Assumed fixed in #271
